### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by iSpartak** [knn90/KNCirclePercentView#1]
Thank you very much for the great component. Quick question, how I can reset percentage to new value and re-start animation?  Let's say you have a calendar and upon new day selected you want to show new value with in the same component. How I can do it w/o removing and adding new instance?

**Comment by knn90** [comment]
First of all, thank for using my component. About the question, you can set
new value to percent property by moving it to KNCirclePercent.h and then
call method startAnimation again. I'm not working now so that I try to
remember what I code. Sorry about that. But this is a good question and I
will modify my code next Monday. Once again thank you. Hope this can help
you somehow

**Comment by iSpartak** [comment]
Thank you knn90. I've tried exactly this suggestion - added percentage property and call animation but it doesnt work as expected. It adds new percentage label on top of exist etc. Would be good if modify your component to support proper update. And thank you again!

**Comment by knn90** [comment]
Hi iSpartak, I've just changed my demo code. Including re-draw circle w/o add a new one. Please check my new demo. Input percent value to TextField and draw. If you have any problem, don't hesitate to let me know. Thank you :)

**Comment by iSpartak** [comment]
Work like a charm!  Thank you very much!

**Comment by knn90** [comment]
Great to hear that. :)
